### PR TITLE
Feat: Make the project into Typescript

### PR DESCRIPTION
**Pull request by whats2000**

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
@whats2000  Thank you for your contribution! Using TypeScript is great 🎉 
There is a small issue: files like `autoload.js` and `waifu-tips.js` may not be able to be moved to the demo directory. At the creation of this repository, I specified a fixed path in the README (`https://cdn.jsdelivr.net/.../live2d-widget@latest/autoload.js`), and it may have been widely reproduced (by reposted blogs etc.). Moving the path of the generated js files might cause problems for many existing users' links (and they may only refer to these blog articles without being proficient in JavaScript), which could lead to confusion. Although I would also like to better organize the directory structure, it might be problematic due to this historical reason. For now, the best approach seems to be to replace `@latest` in the documentation with a fixed version, and wait for future versions to make adjustments.

**Comment by whats2000** [comment]
@stevenjoezhang  Ok, I get it. Let me adjust. My friend is helping me to modularize some functions, such as tools that support localization and custom functions. 

But there are some questions we want to ask:
- We plan to release it to NPM, Considering that the changes may destroy the original program, maybe I should start a new project?

**Comment by stevenjoezhang** [comment]
I think there's a better way: I won't push new tags to GitHub, keeping `@latest` always available, to avoid breaking existing users' code. Then, I'll release a major version update on npm (from 0 to 1), and future documentation will recommend users to use npm's v1 version. This way, we can temporarily get rid of these issues.

**Comment by stevenjoezhang** [comment]
I've pushed some updates; you can rebase and then we can continue to merge and release a new version. I suggest placing files such as `autoload.js`, `live2d.min.js`, `waifu-tips.js`, `waifu-tips.json`, and `waifu.css` in the `dist` directory, as they can still be directly used by users. For advanced users, using a mature TypeScript build process is fine, but for beginners, providing a ready-to-use experience is more user-friendly. As for the `demo` directory, I plan to use it to offer some more creative usage methods (such as using a large language model as a backend to provide dialogue functionality for the characters).

**Comment by whats2000** [comment]
I have done the rebase and the migration for content. You can verify it. 
Umm, but maybe I should try to convert the project into a React/Vue Component, as the one in NPM is almost outdated so far.

**Comment by stevenjoezhang** [comment]
The `live2d-widget` on npm was actually registered by another developer, so I've republished it under `live2d-widgets`:
https://www.npmjs.com/package/live2d-widgets
Further developing components for Vue and ReactJS sounds great. For now, you can use the version from the GitHub repository as a dependency, for example, `npm i stevenjoezhang/live2d-widget#master`.

**Pull request merged**
